// ===== ОБЩИЕ ДАННЫЕ ДЛЯ ОБЕИХ СТРАНИЦ =====
// Здесь хранится весь текст (RU/EN) и список работ.
// Меняешь что-то здесь — изменения подхватят и главная страница, и страница галереи.

const translations = {
  ru: {
    "nav.gallery": "Галерея",
    "nav.about": "Художник",
    "nav.reviews": "Отзывы",
    "nav.contact": "Контакты",
    "hero.eyebrow": "// ЦИФРОВАЯ ГАЛЕРЕЯ — АРХИВ 001",
    "hero.title1": "КИБЕРПАНК",
    "hero.title2": "ОКАЗАЛСЯ МЯГЧЕ,",
    "hero.title3": "ЧЕМ ОБЕЩАЛИ",
    "hero.sub": "Нежные лица в мире бетона и схем.<br>Будущее наступило — и оно плачет, смеётся и любит.",
    "hero.cta": "Смотреть работы",
    "showcase.title": "Избранное",
    "showcase.desc": "Несколько кадров из архива. Полная коллекция — в галерее.",
    "showcase.cta": "Вся галерея",
    "gallery.title": "Галерея",
    "gallery.desc": "Каждая работа — кадр из истории, которая не закончилась. Нажми на работу, чтобы открыть в полном размере.",
    "gallery.count": "работ в архиве",
    "gallery.back": "На главную",
    "about.title": "Художник",
    "about.text1": "Я работаю там, где ржавчина встречается с тёплым светом. Где тело становится частью интерфейса, но душа остаётся нетронутой. Где дети растут под вывесками, а не под звёздами",
    "about.text2": "Мой метод прост: генеративные инструменты как кисть, а не как автопилот. Каждый кадр — это десятки итераций. Я не генерирую — я отбираю. Как архивариус будущего, которое уже наступило.",
    "about.stat1": "работ создано",
    "about.stat2": "года в индустрии",
    "about.stat3": "миров впереди",
    "reviews.title": "Отзывы",
    "reviews.desc": "Журнал отзывов и предложений. Пишите, что думаете о работах — это видят все.",
    "reviews.nameLabel": "Имя",
    "reviews.ratingLabel": "Оценка",
    "reviews.textLabel": "Отзыв",
    "reviews.submit": "Опубликовать",
    "reviews.loading": "Загрузка отзывов...",
    "reviews.empty": "Пока нет отзывов — будь первым.",
    "reviews.sending": "Публикуем...",
    "reviews.success": "Спасибо! Отзыв опубликован.",
    "reviews.errorRating": "Поставь оценку перед отправкой.",
    "reviews.errorGeneric": "Не получилось отправить. Попробуй ещё раз.",
    "contact.title": "Связь",
    "contact.desc": "Заказы, коллаборации, вопросы по работам — пишите.",
    "contact.email": "Почта",
    "footer.made": "Сделано вручную, кадр за кадром",
  },
  en: {
    "nav.gallery": "Gallery",
    "nav.about": "Artist",
    "nav.reviews": "Reviews",
    "nav.contact": "Contact",
    "hero.eyebrow": "// DIGITAL GALLERY — ARCHIVE 001",
    "hero.title1": "CYBERPUNK",
    "hero.title2": "TURNED OUT TO BE SOFTER",
    "hero.title3": "THAN PROMISED",
    "hero.sub": "Tender faces in a world of concrete and diagrams.<br>The future is here — and it cries, laughs and loves.",
    "hero.cta": "View the work",
    "showcase.title": "Selected Works",
    "showcase.desc": "A few frames from the archive. The full collection lives in the gallery.",
    "showcase.cta": "Full Gallery",
    "gallery.title": "Gallery",
    "gallery.desc": "Every piece is a frame from a story that never ended. Click any piece to open it full size.",
    "gallery.count": "works in the archive",
    "gallery.back": "Back home",
    "about.title": "Artist",
    "about.text1": "I work where rust meets warm light. Where the body becomes part of the interface, but the soul remains untouched. Where children grow up beneath shop signs rather than beneath the stars",
    "about.text2": "My method is simple: I use generative tools as a brush, not as an autopilot. Every frame involves dozens of iterations. I don’t generate — I curate. Like an archivist of a future that has already arrived.",
    "about.stat1": "works created",
    "about.stat2": "years in the field",
    "about.stat3": "worlds ahead",
    "reviews.title": "Reviews",
    "reviews.desc": "A log of reviews and suggestions. Tell us what you think — everyone can see it.",
    "reviews.nameLabel": "Name",
    "reviews.ratingLabel": "Rating",
    "reviews.textLabel": "Review",
    "reviews.submit": "Publish",
    "reviews.loading": "Loading reviews...",
    "reviews.empty": "No reviews yet — be the first.",
    "reviews.sending": "Publishing...",
    "reviews.success": "Thanks! Your review is live.",
    "reviews.errorRating": "Please pick a rating first.",
    "reviews.errorGeneric": "Couldn't send it. Try again.",
    "contact.title": "Contact",
    "contact.desc": "Commissions, collaborations, questions about the work — reach out.",
    "contact.email": "Email",
    "footer.made": "Made by hand, frame by frame",
  },
};

// ===== Hero banners (главная страница) =====
const heroBanners = [
  "images/banner-01.png",
  "images/banner-02.png",
  "images/banner-03.png",
];

// ===== Работы — единый источник для витрины на главной и полной галереи =====
// showcase: true — работа попадает в "Избранное" на главной странице
const works = [
  { title: "Телесный архив: ритуал нанесения / Bodily Archive: The Ritual of Inscription", tag: "cyberpunk / портрет", img: "images/work-01.png", showcase: true },
  { title: "Нити памяти / Threads of Memory", tag: "cyberpunk / портрет", img: "images/work-10.png" },
  { title: "Одиночество в режиме ожидания / Loneliness on Standby", tag: "cyberpunk / портрет", img: "images/work-12.png", showcase: true },
  { title: "Точка отправления / Point of Departure", tag: "cyberpunk / city", img: "images/work-07.png" },
  { title: "Солнечный ветер на двоих / Solar Wind for Two", tag: "cyberpunk / портрет", img: "images/work-11.png" },
  { title: "Нежность в тени неона / Tenderness in the Neon Shadow", tag: "cyberpunk / портрет", img: "images/work-14.png", showcase: true },
  { title: "Свет в потоке машин / Light in the Stream of Cars", tag: "cyberpunk / портрет", img: "images/work-13.png" },
  { title: "Невинность на взводе / Innocence on the Trigger", tag: "cyberpunk / портрет", img: "images/work-03.png" },
  { title: "Пост-возраст: эстетика позднего бунта / Post-Age: Aesthetics of Late Rebellion", tag: "cyberpunk / портрет", img: "images/work-05.png" },
  { title: "Тишина на берегу неона / Silence on the Neon Shore", tag: "cyberpunk / портрет", img: "images/work-02.png" },
  { title: "Синтетическая юность: портрет в стиле стрит-гранж / Synthetic Youth: Portrait in Street-Grunge Style", tag: "cyberpunk / портрет", img: "images/work-04.png", showcase: true },
  { title: "Золотой код предков / Golden Code of Ancestors", tag: "cyberpunk / портрет", img: "images/work-06.png" },
  { title: "Эхо ненастоящего утра / Echo of a Simulated Morning", tag: "cyberpunk / city", img: "images/work-08.png" },
  { title: "Город, который дышит ржавчиной / City That Breathes Rust", tag: "cyberpunk / city", img: "images/work-09.png" },
  { title: "Пост-кукольность: эстетика цифрового флирта / Post-Doll Aesthetics: Digital Flirtation", tag: "cyberpunk / портрет", img: "images/work-15.png" },
  { title: "Детство в черном / Childhood in Black", tag: "cyberpunk / портрет", img: "images/work-16.png" },
  { title: "Тёплый ветер для стального странника / Warm Wind for a Steel Wanderer", tag: "cyberpunk / city", img: "images/work-17.png" },
  { title: "Пуховый кокон для синтетической души / Puffer Cocoon for a Synthetic Soul", tag: "cyberpunk / портрет", img: "images/work-20.png" },
];
